name: laser
channels:
  - conda-forge
dependencies:
  - defaults/linux-64::_libgcc_mutex==0.1=main
  - defaults/linux-64::blas==1.0=mkl
  - ca-certificates
  - defaults/linux-64::ld_impl_linux-64==2.44=h153f514_2
  - libstdcxx-ng
  - pytorch/noarch::pytorch-mutex==1.0=cpu
  - defaults/noarch::tzdata==2025b=h04d1e81_0
  - defaults/linux-64::libgomp==11.2.0=h1234567_1
  - defaults/linux-64::_openmp_mutex==5.1=1_gnu
  - defaults/linux-64::libgcc-ng==11.2.0=h1234567_1
  - defaults/linux-64::aom==3.12.1=h7934f7d_0
  - defaults/linux-64::bzip2==1.0.8=h5eee18b_6
  - defaults/linux-64::dav1d==1.2.1=h5eee18b_0
  - defaults/linux-64::expat==2.7.1=h6a678d5_0
  - defaults/linux-64::giflib==5.2.2=h5eee18b_0
  - defaults/linux-64::gmp==6.3.0=h6a678d5_0
  - defaults/linux-64::graphite2==1.3.14=h295c915_1
  - defaults/linux-64::icu==73.1=h6a678d5_0
  - defaults/linux-64::jpeg==9f=h5ce9db8_0
  - defaults/linux-64::lame==3.100=h7b6447c_0
  - defaults/linux-64::lerc==4.0.0=h6a678d5_0
  - defaults/linux-64::libdeflate==1.22=h5eee18b_0
  - defaults/linux-64::libffi==3.4.4=h6a678d5_1
  - defaults/linux-64::libiconv==1.16=h5eee18b_3
  - defaults/linux-64::libnsl==2.0.0=h5eee18b_0
  - defaults/linux-64::libogg==1.3.5=h27cfd23_1
  - defaults/linux-64::libopenjpeg==2.5.4=hee96239_0
  - defaults/linux-64::libopus==1.3.1=h5eee18b_1
  - defaults/linux-64::libuuid==1.41.5=h5eee18b_0
  - defaults/linux-64::libvpx==1.13.1=h6a678d5_0
  - defaults/linux-64::libwebp-base==1.3.2=h5eee18b_1
  - defaults/linux-64::libzlib==1.3.1=hb25bd0a_0
  - defaults/linux-64::lz4-c==1.9.4=h6a678d5_1
  - defaults/linux-64::ncurses==6.5=h7934f7d_0
  - defaults/linux-64::openh264==2.6.0=he621ea3_0
  - openssl
  - defaults/linux-64::pixman==0.46.4=h7934f7d_0
  - defaults/linux-64::pthread-stubs==0.3=h0ce48e5_1
  - defaults/linux-64::tbb==2021.8.0=hdb19cb5_0
  - defaults/linux-64::xorg-libxau==1.0.12=h9b100fa_0
  - defaults/linux-64::xorg-libxdmcp==1.1.5=h9b100fa_0
  - defaults/linux-64::xorg-xorgproto==2024.1=h5eee18b_1
  - defaults/linux-64::xz==5.6.4=h5eee18b_1
  - defaults/linux-64::libvorbis==1.3.7=h7b6447c_0
  - defaults/linux-64::libxcb==1.17.0=h9b100fa_0
  - defaults/linux-64::mpfr==4.2.1=h5eee18b_0
  - defaults/linux-64::readline==8.3=hc2a1206_0
  - defaults/linux-64::zlib==1.3.1=hb25bd0a_0
  - defaults/linux-64::zstd==1.5.7=h11fc155_0
  - defaults/linux-64::intel-openmp==2023.0.0=h9e868ea_25371
  - defaults/linux-64::libpng==1.6.50=h2ed474d_0
  - defaults/linux-64::libtheora==1.2.0=h32ad74f_1
  - defaults/linux-64::libtiff==4.7.0=hde9077f_0
  - libxml2
  - defaults/linux-64::mpc==1.3.1=h5eee18b_0
  - defaults/linux-64::pcre2==10.46=hf426167_0
  - defaults/linux-64::sqlite==3.50.2=hb25bd0a_1
  - defaults/linux-64::xorg-libx11==1.8.12=h9b100fa_1
  - defaults/linux-64::freetype==2.13.3=h4a9f257_0
  - defaults/linux-64::lcms2==2.16=h92b89f2_1
  - libarchive
  - defaults/linux-64::libglib==2.84.4=h77a78f3_0
  - defaults/linux-64::libwebp==1.3.2=h9f374a3_1
  - defaults/linux-64::mkl==2023.1.0=h213fc3f_46344
  - defaults/linux-64::tk==8.6.15=h54e0aa7_0
  - defaults/linux-64::xorg-libxext==1.3.6=h9b100fa_0
  - defaults/linux-64::xorg-libxrender==0.9.12=h9b100fa_0
  - fontconfig
  - defaults/linux-64::openjpeg==2.5.4=h4e0627c_0
  - defaults/linux-64::python==3.9.24=h0dcde21_1
  - cairo
  - certifi
  - defaults/noarch::charset-normalizer==3.3.2=pyhd3eb1b0_0
  - defaults/linux-64::filelock==3.17.0=py39h06a4308_0
  - defaults/linux-64::gmpy2==2.2.1=py39h5eee18b_0
  - defaults/linux-64::idna==3.7=py39h06a4308_0
  - defaults/linux-64::leptonica==1.82.0=hfdeec58_3
  - defaults/linux-64::markupsafe==3.0.2=py39h5eee18b_0
  - defaults/linux-64::mkl-service==2.4.0=py39h5eee18b_2
  - defaults/linux-64::mpmath==1.3.0=py39h06a4308_0
  - defaults/linux-64::networkx==3.2.1=py39h06a4308_0
  - defaults/linux-64::pillow==11.1.0=py39hac6e08b_1
  - defaults/linux-64::pycparser==2.23=py39h06a4308_0
  - defaults/linux-64::pysocks==1.7.1=py39h06a4308_0
  - defaults/linux-64::setuptools==80.9.0=py39h06a4308_0
  - defaults/linux-64::typing_extensions==4.15.0=py39h06a4308_0
  - defaults/linux-64::wheel==0.45.1=py39h06a4308_0
  - defaults/linux-64::cffi==2.0.0=py39h4eded50_0
  - harfbuzz
  - defaults/linux-64::jinja2==3.1.6=py39h06a4308_0
  - defaults/noarch::pip==25.2=pyhc872135_1
  - defaults/linux-64::sympy==1.14.0=py39h06a4308_0
  - tesseract
  - defaults/linux-64::brotlicffi==1.0.9.2=py39h6a678d5_1
  - ffmpeg
  - defaults/linux-64::urllib3==2.5.0=py39h06a4308_0
  - defaults/linux-64::requests==2.32.5=py39h06a4308_0
  - defaults/linux-64::mkl_fft==1.3.11=py39h5eee18b_0
  - defaults/linux-64::mkl_random==1.2.8=py39h1128e8f_0
  - defaults/linux-64::numpy==2.0.1=py39h5f9d8c6_1
  - pytorch/linux-64::torchaudio==2.0.2=py39_cpu
  - torchvision
  - conda-pack
prefix: /opt/anaconda3/envs/laser
